# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 03:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0.0, verbose_name='\u7528\u6237\u4f59\u989d')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to=settings.AUTH_USER_MODEL, verbose_name='\u6240\u5c5e\u7528\u6237')),
            ],
            options={
                'db_table': 'users_balance',
                'verbose_name': '\u7528\u6237\u7ed3\u7b97\u8868',
                'verbose_name_plural': '\u7528\u6237\u7ed3\u7b97\u8868',
            },
        ),
    ]
