# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 03:11
from __future__ import unicode_literals

import annoying.fields
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userbalance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbalance',
            name='id',
        ),
        migrations.AlterField(
            model_name='userbalance',
            name='user',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='balance', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='\u6240\u5c5e\u7528\u6237'),
        ),
    ]
