# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170417_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatar/%Y/%m/%d/'),
        ),
    ]
