# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 14:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookshelfTimestamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u6240\u5c5e\u7528\u6237')),
            ],
            options={
                'db_table': 'bookshelf_timestamp',
                'verbose_name': '\u4e66\u67b6\u66f4\u65b0\u65f6\u95f4\u8868',
                'verbose_name_plural': '\u4e66\u67b6\u66f4\u65b0\u65f6\u95f4\u8868',
            },
        ),
        migrations.RemoveField(
            model_name='bookshelf',
            name='is_bought',
        ),
    ]
