# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_auto_20170517_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookshelf',
            name='create_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='\u52a0\u5165\u65f6\u95f4'),
            preserve_default=False,
        ),
    ]
