language: python
python:
  - "2.7"
install:
  - "pip install -r requirements.txt"
  - "pip install -r requirements-test.txt"
script:
  - "[ $TRAVIS_BRANCH == \"guoyaoxing\" ] && ssh -o \"StrictHostKeyChecking no\" master@oott.me \"ls /www\""
