language: python
python:
  - "2.7"
install:
  - "pip install -r requirements.txt"
  - "pip install -r requirements-test.txt"
addons:
  apt:
    packages:
      - sshpass
script:
  - "[ $TRAVIS_BRANCH == \"guoyaoxing\" ] && sshpass -p \"${guoyaoxing_password}\" ssh -o \"StrictHostKeyChecking no\" ${guoyaoxing_username}@oott.me \"ls /www\""
