# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-14 14:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'bookcase',
                'verbose_name': '\u4e66\u67b6\u8868',
                'verbose_name_plural': '\u4e66\u67b6\u8868',
            },
        ),
        migrations.CreateModel(
            name='BookClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_class_name', models.CharField(max_length=30, verbose_name='\u56fe\u4e66\u7c7b\u540d')),
            ],
            options={
                'db_table': 'book_class',
                'verbose_name': '\u56fe\u4e66\u7c7b\u8868',
                'verbose_name_plural': '\u56fe\u4e66\u7c7b\u8868',
            },
        ),
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='\u4e66\u540d')),
                ('price', models.FloatField(verbose_name='\u4ef7\u683c')),
                ('data', models.TextField(verbose_name='\u7b80\u4ecb')),
                ('cover', models.ImageField(blank=True, upload_to='cover/%Y/%m/%d/', verbose_name='\u56fe\u7247')),
                ('author', models.CharField(max_length=30, verbose_name='\u4f5c\u8005')),
                ('score', models.FloatField(verbose_name='\u8bc4\u5206')),
                ('time', models.DateTimeField(verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('chapter', models.CharField(max_length=30, verbose_name='\u6700\u8fd1\u66f4\u65b0\u7ae0\u8282')),
                ('book_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshopping.BookClass', verbose_name='\u56fe\u4e66\u7c7b\u8868')),
            ],
            options={
                'db_table': 'book_info',
                'verbose_name': '\u56fe\u4e66\u4fe1\u606f\u8868',
                'verbose_name_plural': '\u56fe\u4e66\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='BuyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('book_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshopping.BookInfo', verbose_name='\u56fe\u4e66\u4fe1\u606f\u8868')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'db_table': 'buy_record',
                'verbose_name': '\u8d2d\u4e70\u8868',
                'verbose_name_plural': '\u8d2d\u4e70\u8868',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_time', models.DateTimeField(verbose_name='\u8bc4\u8bba\u65f6\u95f4')),
                ('comment_contain', models.TextField(verbose_name='\u8bc4\u8bba\u5185\u5bb9')),
                ('comment_score', models.IntegerField(verbose_name='\u8bc4\u8bba\u5206\u6570')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('book_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshopping.BookInfo', verbose_name='\u56fe\u4e66\u4fe1\u606f\u8868')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='bookshopping.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DownloadRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('book_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshopping.BookInfo', verbose_name='\u56fe\u4e66\u4fe1\u606f\u8868')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'db_table': 'download_record',
                'verbose_name': '\u4e0b\u8f7d\u8868',
                'verbose_name_plural': '\u4e0b\u8f7d\u8868',
            },
        ),
        migrations.CreateModel(
            name='ReadRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('book_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshopping.BookInfo', verbose_name='\u56fe\u4e66\u4fe1\u606f\u8868')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'db_table': 'read_record',
                'verbose_name': '\u5df2\u8bfb\u8868',
                'verbose_name_plural': '\u5df2\u8bfb\u8868',
            },
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_time', models.DateTimeField(verbose_name='\u8d2d\u4e70\u65e5\u671f')),
                ('price', models.FloatField(verbose_name='\u82b1\u8d39')),
                ('book_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshopping.BookInfo', verbose_name='\u56fe\u4e66\u4fe1\u606f\u8868')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'db_table': 'shopping_list',
                'verbose_name': '\u8d26\u5355\u8868',
                'verbose_name_plural': '\u8d26\u5355\u8868',
            },
        ),
        migrations.AddField(
            model_name='bookcase',
            name='book_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshopping.BookInfo', verbose_name='\u56fe\u4e66\u4fe1\u606f\u8868'),
        ),
        migrations.AddField(
            model_name='bookcase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237'),
        ),
    ]
