# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transform', '0001_initial'),
        ('bookshopping', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '\u8bc4\u8bba\u8868', 'verbose_name_plural': '\u8bc4\u8bba\u8868'},
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transform.Transform',
                                    verbose_name='\u7535\u5b50\u4e66\u8f6c\u6362\u7c7b'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_score',
            field=models.IntegerField(verbose_name='\u8bc4\u5206'),
        ),
    ]
