# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshopping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookshelf',
            name='is_bought',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u5df2\u7ecf\u8d2d\u4e70'),
        ),
    ]
