# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app.transform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transform',
            name='origin',
            field=models.FileField(upload_to='transform/%Y/%m/%d/'),
        ),
    ]
