# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 19:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transform', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='\u4e66\u540d')),
                ('author', models.CharField(max_length=30, verbose_name='\u4f5c\u8005')),
                ('cover', models.ImageField(blank=True, upload_to='cover/%Y/%m/%d/', verbose_name='\u56fe\u7247')),
                ('introduction', models.TextField(verbose_name='\u7b80\u4ecb')),
                ('price', models.FloatField(verbose_name='\u4ef7\u683c\uff08\u4e66\u5e01\uff09')),
                ('score', models.FloatField(verbose_name='\u8bc4\u5206')),
                ('total_chapter', models.IntegerField(verbose_name='\u7ae0\u8282\u6570\u91cf')),
                ('latest_chapter_text', models.CharField(max_length=64, verbose_name='\u6700\u8fd1\u66f4\u65b0\u7ae0\u8282')),
                ('allow_trial', models.BooleanField(default=True, verbose_name='\u662f\u5426\u5141\u8bb8\u8bd5\u8bfb')),
                ('trial_chapter', models.PositiveIntegerField(default=1, verbose_name='\u8bd5\u8bfb\u5141\u8bb8\u7ae0\u8282')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'db_table': 'book',
                'verbose_name': '\u56fe\u4e66\u8868',
                'verbose_name_plural': '\u56fe\u4e66\u8868',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u5206\u7c7b\u540d\u79f0')),
            ],
            options={
                'db_table': 'category',
                'verbose_name': '\u56fe\u4e66\u5206\u7c7b\u8868',
                'verbose_name_plural': '\u56fe\u4e66\u5206\u7c7b\u8868',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='\u8bc4\u8bba\u5185\u5bb9')),
                ('score', models.FloatField(default=0, verbose_name='\u8bc4\u5206')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='\u8bc4\u8bba\u65f6\u95f4')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book', verbose_name='\u6240\u5c5e\u56fe\u4e66')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='book.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u6240\u5c5e\u7528\u6237')),
            ],
            options={
                'db_table': 'comment',
                'verbose_name': '\u8bc4\u8bba\u8868',
                'verbose_name_plural': '\u8bc4\u8bba\u8868',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Category', verbose_name='\u6240\u5c5e\u5206\u7c7b'),
        ),
        migrations.AddField(
            model_name='book',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transform.Transform', verbose_name='\u56fe\u4e66\u6587\u4ef6'),
        ),
    ]
