# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=30, verbose_name='\u4f5c\u8005'),
        ),
        migrations.AlterField(
            model_name='book',
            name='introduction',
            field=models.TextField(blank=True, verbose_name='\u7b80\u4ecb'),
        ),
        migrations.AlterField(
            model_name='book',
            name='latest_chapter_text',
            field=models.CharField(blank=True, max_length=64, verbose_name='\u6700\u8fd1\u66f4\u65b0\u7ae0\u8282'),
        ),
        migrations.AlterField(
            model_name='book',
            name='total_chapter',
            field=models.IntegerField(default=0, verbose_name='\u7ae0\u8282\u6570\u91cf'),
        ),
    ]
