# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 03:04
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20170517_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='cover/%Y/%m/%d/', verbose_name='\u56fe\u7247'),
        ),
    ]
