# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20170519_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, upload_to='cover/%Y/%m/%d/', verbose_name='\u56fe\u7247'),
        ),
    ]
