# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_searchhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='key',
            field=models.CharField(db_index=True, max_length=128, verbose_name='\u641c\u7d22\u5173\u952e\u5b57'),
        ),
    ]
