# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20170517_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyrecord',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='\u82b1\u8d39\uff08\u4e66\u5e01\uff09'),
        ),
    ]
