# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 12:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personal', '0003_buyrecord_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='\u91d1\u989d\uff08\u4e66\u5e01\uff09')),
                ('status', models.IntegerField(choices=[(0, '\u7b49\u5f85\u4ed8\u6b3e'), (1, '\u4ed8\u6b3e\u5b8c\u6210'), (2, '\u4ed8\u6b3e\u51fa\u9519')], verbose_name='\u5f53\u524d\u72b6\u6001')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modify_timestamp', models.DateTimeField(auto_now=True, verbose_name='\u6700\u540e\u4fee\u6539\u65f6\u95f4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u6240\u5c5e\u7528\u6237')),
            ],
            options={
                'db_table': 'deposit_record',
                'verbose_name': '\u5145\u503c\u8bb0\u5f55\u8868',
                'verbose_name_plural': '\u5145\u503c\u8bb0\u5f55\u8868',
            },
        ),
        migrations.AlterModelOptions(
            name='readrecord',
            options={'verbose_name': '\u5df2\u8bfb\u4e66\u7c4d\u8868', 'verbose_name_plural': '\u5df2\u8bfb\u4e66\u7c4d\u8868'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='book',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.FloatField(default=0, verbose_name='\u91d1\u989d\u53d8\u52a8\uff08\u4e66\u5e01\uff09'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='', max_length=256, verbose_name='\u5546\u54c1\u540d\u79f0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, verbose_name='\u8ba2\u5355\u5907\u6ce8'),
        ),
    ]
