# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 13:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_progress', models.BooleanField(default=False, verbose_name='\u662f\u5426\u540c\u6b65\u8fdb\u5ea6')),
                ('clean_cache', models.BooleanField(default=False, verbose_name='\u662f\u5426\u81ea\u52a8\u6e05\u9664\u7f13\u5b58')),
                ('display_progress', models.BooleanField(default=True, verbose_name='\u662f\u5426\u663e\u793a\u9605\u8bfb\u8fdb\u5ea6')),
                ('wifi_download_only', models.BooleanField(default=True, verbose_name='\u662f\u5426\u4ec5\u7528 WiFi \u4e0b\u8f7d')),
                ('accept_push', models.BooleanField(default=True, verbose_name='\u662f\u5426\u63a5\u53d7\u63a8\u9001')),
                ('auto_buy_chapter', models.BooleanField(default=False, verbose_name='\u662f\u5426\u81ea\u52a8\u8d2d\u4e70\u7ae0\u8282')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_options',
                'verbose_name': '\u7528\u6237\u9009\u9879',
                'verbose_name_plural': '\u7528\u6237\u9009\u9879',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=64, verbose_name='\u6635\u79f0')),
                ('phone', models.CharField(max_length=20, verbose_name='\u624b\u673a\u53f7\u7801')),
                ('signature', models.TextField(verbose_name='\u4e2a\u6027\u7b7e\u540d')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
                'verbose_name': '\u7528\u6237\u8be6\u60c5',
                'verbose_name_plural': '\u7528\u6237\u8be6\u60c5',
            },
        ),
    ]
