# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 02:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_timestamp', models.DateField(auto_now_add=True, db_index=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u53d1\u9001\u7528\u6237')),
            ],
            options={
                'db_table': 'check',
                'verbose_name': '\u7b7e\u5230\u8868',
                'verbose_name_plural': '\u7b7e\u5230\u8868',
            },
        ),
    ]
