# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 02:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='check_timestamp',
            field=models.DateField(auto_now_add=True, db_index=True, verbose_name='\u7b7e\u5230\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='check',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237'),
        ),
    ]
