# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u96be\u5ea6')),
                ('difficulty', models.IntegerField(verbose_name='\u96be\u5ea6\u7cfb\u6570')),
            ],
            options={
                'db_table': 'difficulty',
                'verbose_name': '\u96be\u5ea6\u8868',
                'verbose_name_plural': '\u96be\u5ea6\u8868',
            },
        ),
        migrations.CreateModel(
            name='FillBlanks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='\u5206\u503c')),
                ('question', models.TextField(verbose_name='\u9898\u76ee')),
                ('answer', models.CharField(max_length=50, verbose_name='\u7b54\u6848')),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionbank.Difficulty', verbose_name='\u96be\u5ea6')),
            ],
            options={
                'db_table': 'fill_blanks',
                'verbose_name': '\u586b\u7a7a\u9898\u8868',
                'verbose_name_plural': '\u586b\u7a7a\u9898\u8868',
            },
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='\u5206\u503c')),
                ('question', models.TextField(verbose_name='\u9898\u76ee')),
                ('answer', models.BooleanField(verbose_name='\u7b54\u6848')),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionbank.Difficulty', verbose_name='\u96be\u5ea6')),
            ],
            options={
                'db_table': 'judge',
                'verbose_name': '\u5224\u65ad\u9898\u8868',
                'verbose_name_plural': '\u5224\u65ad\u9898\u8868',
            },
        ),
        migrations.CreateModel(
            name='MultiSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='\u5206\u503c')),
                ('question', models.TextField(verbose_name='\u9898\u76ee')),
                ('selectionA', models.TextField(verbose_name='\u9009\u9879A')),
                ('selectionB', models.TextField(verbose_name='\u9009\u9879B')),
                ('selectionC', models.TextField(verbose_name='\u9009\u9879C')),
                ('selectionD', models.TextField(verbose_name='\u9009\u9879D')),
                ('selectionE', models.TextField(verbose_name='\u9009\u9879E')),
                ('selectionF', models.TextField(verbose_name='\u9009\u9879F')),
                ('answer', models.CharField(max_length=6, verbose_name='\u7b54\u6848')),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionbank.Difficulty', verbose_name='\u96be\u5ea6')),
            ],
            options={
                'db_table': 'multi_selection',
                'verbose_name': '\u591a\u9009\u9898\u8868',
                'verbose_name_plural': '\u591a\u9009\u9898\u8868',
            },
        ),
        migrations.CreateModel(
            name='SingleSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='\u5206\u503c')),
                ('question', models.TextField(verbose_name='\u9898\u76ee')),
                ('selectionA', models.TextField(verbose_name='\u9009\u9879A')),
                ('selectionB', models.TextField(verbose_name='\u9009\u9879B')),
                ('selectionC', models.TextField(verbose_name='\u9009\u9879C')),
                ('selectionD', models.TextField(verbose_name='\u9009\u9879D')),
                ('answer', models.CharField(max_length=1)),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionbank.Difficulty', verbose_name='\u96be\u5ea6')),
            ],
            options={
                'db_table': 'single_selection',
                'verbose_name': '\u5355\u9009\u9898\u8868',
                'verbose_name_plural': '\u5355\u9009\u9898\u8868',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u79d1\u76ee\u540d')),
            ],
            options={
                'db_table': 'subjects',
                'verbose_name': '\u79d1\u76ee\u8868',
                'verbose_name_plural': '\u79d1\u76ee\u8868',
            },
        ),
        migrations.AddField(
            model_name='singleselection',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionbank.Subject', verbose_name='\u79d1\u76ee\u8868'),
        ),
        migrations.AddField(
            model_name='multiselection',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionbank.Subject', verbose_name='\u79d1\u76ee\u8868'),
        ),
        migrations.AddField(
            model_name='judge',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionbank.Subject', verbose_name='\u79d1\u76ee\u8868'),
        ),
        migrations.AddField(
            model_name='fillblanks',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionbank.Subject', verbose_name='\u79d1\u76ee\u8868'),
        ),
    ]
