# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='action_type',
            field=models.CharField(blank=True, choices=[('', '\u672a\u4f7f\u7528'), ('comment', '\u8bc4\u8bba'), ('like', '\u559c\u6b22'), ('like', '\u4e0d\u559c\u6b22')], max_length=64, verbose_name='\u52a8\u4f5c\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='notify',
            name='target',
            field=models.IntegerField(blank=True, default=0, verbose_name='\u76ee\u6807ID'),
        ),
        migrations.AlterField(
            model_name='notify',
            name='target_type',
            field=models.CharField(blank=True, choices=[('', '\u672a\u4f7f\u7528'), ('book', '\u4e66\u7c4d'), ('video', '\u89c6\u9891'), ('order', '\u8ba2\u5355')], max_length=64, verbose_name='\u76ee\u6807\u7c7b\u578b'),
        ),
    ]
